/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "eventry.h"

int *
evenp_1_svc(intpair *argp, struct svc_req *rqstp)
{

	static int result,i,sum=0;
	
	for(i=1;i<=50;i++)
	{
		if(i%2==1)
			sum=sum+i;
	}
	result=sum;
	return &result;
}
