/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operation.h"

int *
fact_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;
	int n1,n2,ch1;
	n1=argp->a;
	n2=argp->b;	
	ch1=argp->ch;
	switch(ch1)
	{
		case 1:
		printf("Addidtion");
		result=n1+n2;
		break;
		case 2:
		printf("Substraction");
		result=n1-n2;
		break;
		case 3:
		printf("Multiplication");
		result=n1*n2;
		break;
		case 4:
		printf("Div");
		result=n1/n2;
		break;
		default:
		printf("\nWrong!!1");
		break;
	}

	return &result;
}
