/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operation.h"


void
fact_prog_1(char *host,int a,int b,int ch)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  fact_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FACT_PROG, FACT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	fact_1_arg.a=a;
	fact_1_arg.b=b;
	fact_1_arg.ch=ch;
	result_1 = fact_1(&fact_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\nresults=%d",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int a,b,ch,y;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	do
	{
		
		printf("enter 2 no");
		scanf("%d%d",&a,&b);
		printf("\n1.Add \n2.Sub\n 3.mul\n4.Div");
		printf("\nEnter ur choice");
		scanf("%d",&ch);
		
		fact_prog_1 (host,a,b,ch);
		
			
		printf("conrinue");
		scanf("%d",&y);
	}while(y==1);
	
exit (0);
}
